spring.application.name=MatchDay
spring.mvc.hiddenmethod.filter.enabled=true
# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/matchday?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1973197419952006Penkovi
logging.level.org.hibernate.persister.entity=ERROR

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikolapenkov0306@gmail.com
spring.mail.password=tslj fgln umtk ukvf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true